# @BASE_URL=http://3.36.49.195:3000/api/wr/v1
@BASE_URL=http://localhost:3000/api/wr/v1


POST {{BASE_URL}}/user
Content-Type: application/json

{
    "id": "test1",
	"password": "asdfasdf",
	"name": "우사인",
	"birth": "2000-01-01",
	"sex": "male",
	"phone": "010-1111-1111"
}

###

POST {{BASE_URL}}/user
Content-Type: application/json

{
    "id": "test2",
	"password": "asdfasdf",
	"name": "홍길동",
	"birth": "2000-01-01",
	"sex": "male",
	"phone": "010-1111-1112"
}

###
POST {{BASE_URL}}/user
Content-Type: application/json

{
    "id": "test3",
	"password": "asdfasdf",
	"name": "김볼트",
	"birth": "2000-01-01",
	"sex": "male",
	"phone": "010-1111-1113"
}

###
POST {{BASE_URL}}/user
Content-Type: application/json

{
    "id": "test4",
	"password": "asdfasdf",
	"name": "김국영",
	"birth": "2000-01-01",
	"sex": "male",
	"phone": "010-1111-1114"
}

###
POST {{BASE_URL}}/user
Content-Type: application/json

{
    "id": "test5",
	"password": "asdfasdf",
	"name": "김영희",
	"birth": "2000-01-01",
	"sex": "male",
	"phone": "010-1111-1115"
}

###
POST {{BASE_URL}}/user
Content-Type: application/json

{
    "id": "test6",
	"password": "asdfasdf",
	"name": "정태영",
	"birth": "2000-01-01",
	"sex": "male",
	"phone": "010-1111-1116"
}

###

POST {{BASE_URL}}/user
Content-Type: application/json

{
    "id": "test7",
	"password": "asdfasdf",
	"name": "알렉스",
	"birth": "2000-01-01",
	"sex": "male",
	"phone": "010-1111-1117"
}

###

POST {{BASE_URL}}/user
Content-Type: application/json

{
    "id": "test8",
	"password": "asdfasdf",
	"name": "김철수",
	"birth": "2000-01-01",
	"sex": "male",
	"phone": "010-1111-1118"
}
###
POST {{BASE_URL}}/user
Content-Type: application/json

{
    "id": "test9",
	"password": "asdfasdf",
	"name": "오영주",
	"birth": "2000-01-01",
	"sex": "male",
	"phone": "010-1111-1119"
}